---
- hosts: all
  remote_user: root
  become: true
  become_method: sudo
  vars:
    compose_directory: "/data/hosting.luanti.ch"
  tasks:
    - name: create project dir
      file:
        path: "{{ compose_directory }}"
        state: directory

    - name: Copy files
      template:
        src: "{{item}}"
        dest: "{{compose_directory}}/{{item}}"
      with_items:
       - "docker-compose.yml"
       - "haproxy.cfg"
       - "redirect.conf"
       - ".env"

    - name: Update deployment
      shell: |
        docker-compose pull
        docker-compose up -d mt-hosting-active
        sleep 10
        docker-compose up -d mt-hosting-passive
        docker-compose up -d
      args:
        chdir: "{{compose_directory}}"
