---
- hosts: all
  remote_user: root
  become: true
  become_method: sudo
  vars:
    compose_directory: "/data/hosting.minetest.ch"
  tasks:
    - name: create project dir
      file:
        path: "{{ compose_directory }}"
        state: directory

    - name: Copy files
      template:
        src: "{{item}}"
        dest: "{{compose_directory}}/{{item}}"
      with_items:
       - "docker-compose.yml"
       - "haproxy.cfg"
       - ".env"
       - "public.env"

    - name: Copy env file
      copy:
        content: "{{ SSH_KEY }}"
        dest: "{{compose_directory}}/id_rsa"

    - name: Wait for container start
      pause:
        seconds: 2

    - name: Update active deployment
      docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        services:
         - mt-hosting-active

    - name: Wait for container start
      pause:
        seconds: 10

    - name: Update passive deployment
      docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        services:
         - mt-hosting-passive

    - name: Start auxilliary services
      docker_compose:
        project_src: "{{ compose_directory }}"
        remove_orphans: yes
