---
- hosts: all
  remote_user: root
  become: true
  become_method: sudo
  vars:
    compose_directory: "/data/hosting.minetest.ch"
  tasks:
    - name: create project dir
      file:
        path: "{{ compose_directory }}"
        state: directory

    - name: Copy files
      template:
        src: "{{item}}"
        dest: "{{compose_directory}}/{{item}}"
      with_items:
       - "docker-compose.yml"
       - "haproxy.cfg"
       - ".env"

    - name: Pull image
      shell: |
        docker-compose pull

    - name: Update active deployment
      shell: |
        docker-compose up -d mt-hosting-active
      args:
        chdir: "{{compose_directory}}"

    - name: Wait for container start
      pause:
        seconds: 10

    - name: Update passive deployment
      shell: |
        docker-compose up -d mt-hosting-passive
      args:
        chdir: "{{compose_directory}}"

    - name: Start auxilliary services
      shell: |
        docker-compose up -d
      args:
        chdir: "{{compose_directory}}"
