version: "2"

services:
 mt-hosting-worker:
  image: ghcr.io/minetest-hosting/mt-hosting-manager:latest
  working_dir: /data
  environment:
   - ENABLE_WORKER=true
  env_file:
   - .env
  volumes:
   - "./data/db:/data"
   - "./id_rsa:/id_rsa"
  labels:
    - "promtail=true"

 mt-hosting-green: &hosting
  image: ghcr.io/minetest-hosting/mt-hosting-manager:latest
  working_dir: /data
  networks:
   - default
   - terminator
  env_file:
   - .env
  volumes:
   - "./data/db:/data"
  labels:
    - "promtail=true"
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.mthosting.rule=Host(`hosting.minetest.ch`)"
    - "traefik.http.routers.mthosting.entrypoints=websecure"
    - "traefik.http.routers.mthosting.tls.certresolver=default"
    - "traefik.http.services.mthosting.loadbalancer.server.port=8080"
    - "traefik.http.services.mthosting.loadbalancer.healthCheck.path=/api/healthcheck"
    - "traefik.http.services.mthosting.loadbalancer.healthCheck.interval=10s"
    - "traefik.http.services.mthosting.loadbalancer.healthCheck.timeout=1s"
    - "traefik.http.middlewares.mthosting-retry.retry.attempts=5"
    - "traefik.http.middlewares.mthosting-retry.retry.initialinterval=200ms"

 mt-hosting-blue:
  <<: *hosting

networks:
 terminator:
  external: true
