version: "2"

services:
 redis:
  image: redis:7.2.4-alpine
  restart: always
  labels:
   - "promtail=true"

 mt-hosting-worker:
  image: ghcr.io/minetest-hosting/mt-hosting-manager:latest
  working_dir: /data
  stop_grace_period: 5m
  depends_on:
   - redis
  environment:
   - ENABLE_WORKER=true
  env_file:
   - .env
  volumes:
   - "./data:/data"
   - "./id_rsa:/id_rsa"
  labels:
    - "promtail=true"

 mt-hosting-green: &hosting
  image: ghcr.io/minetest-hosting/mt-hosting-manager:latest
  working_dir: /data
  depends_on:
   - redis
  networks:
   - default
   - terminator
  env_file:
   - .env
  volumes:
   - "./data:/data"
  labels:
    - "promtail=true"

 mt-hosting-blue:
  <<: *hosting

 haproxy:
  image: haproxy:2.9.1
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - mt-hosting-blue
   - mt-hosting-green
  labels:
    - "promtail=true"
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.mthosting.rule=Host(`hosting.minetest.ch`)"
    - "traefik.http.services.mthosting.loadbalancer.server.port=80"
    - "traefik.http.routers.mthosting.entrypoints=websecure"
    - "traefik.http.routers.mthosting.tls.certresolver=default"
  volumes:
   - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
  logging:
   options:
    max-size: 50m


networks:
 terminator:
  external: true
