version: "2"

services:
 redis:
  image: redis:7.2.4-alpine
  restart: always
  labels:
   - "promtail=true"

 postgres:
  image: postgres:16.1
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  labels:
   - "promtail=true"
  volumes:
   - "./data/postgres:/var/lib/postgresql/data"
  command:
   - "postgres"
   - "-c"
   - "shared_buffers=4GB"
   - "-c"
   - "synchronous_commit=off"
  logging:
   options:
    max-size: 50m

 mt-hosting-worker:
  image: ghcr.io/minetest-hosting/mt-hosting-manager:latest
  working_dir: /data
  stop_grace_period: 5m
  depends_on:
   - redis
   - postgres
  environment:
   - ENABLE_WORKER=true
  env_file:
   - public.env
   - .env
  volumes:
   - "./data:/data"
   - "./id_rsa:/id_rsa"
  labels:
    - "promtail=true"

 mt-hosting-green: &hosting
  image: ghcr.io/minetest-hosting/mt-hosting-manager:latest
  working_dir: /data
  depends_on:
   - redis
   - postgres
  networks:
   - default
   - terminator
  env_file:
   - public.env
   - .env
  volumes:
   - "./data:/data"
   - "./id_rsa:/id_rsa"
  labels:
    - "promtail=true"

 mt-hosting-blue:
  <<: *hosting

 haproxy:
  image: haproxy:2.9.3
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - mt-hosting-blue
   - mt-hosting-green
  labels:
    - "promtail=true"
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.mthosting.rule=Host(`hosting.minetest.ch`)"
    - "traefik.http.services.mthosting.loadbalancer.server.port=80"
    - "traefik.http.routers.mthosting.entrypoints=websecure"
    - "traefik.http.routers.mthosting.tls.certresolver=default"
  volumes:
   - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
  logging:
   options:
    max-size: 50m


networks:
 terminator:
  external: true
