name: migrate-pg

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    concurrency: deployment
    steps:
    - uses: actions/checkout@v4
    - name: Prepare environment
      run: |
        id
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan hosting.minetest.ch >> ~/.ssh/known_hosts
        chmod -R 700 ~/.ssh
        ansible-galaxy collection install community.general
        echo "${{ secrets.VAULT_PASS }}" > ~/.vault_pass.txt
    - name: Run ansible
      run: |
        ansible-playbook -i hosts --vault-password-file ~/.vault_pass.txt --private-key ~/.ssh/id_rsa migrate-pg.yml
